name: 京东极速签到

on:
  workflow_dispatch:
  schedule:
    - cron: '5 7 * * *'
  watch:
    types: started
  repository_dispatch:
    types: jd_speed_sign
jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        run: |
          git clone -b master https://github.com/yysy/jd_scripts.git ~/jd_scripts
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@v2 # 使用 GitHub 官方的缓存 Action。
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }} # 使用 package-lock.json 的 Hash 作为缓存的 key。也可以使用 package.json 代替
      - name: npm install
        run: |
          cd ~/jd_scripts
          npm install
      - name: '运行 【京东极速版签到】'
        run: |
          cd ~/jd_scripts
          node jd_speed_sign.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          JD_DEBUG: ${{ secrets.JD_DEBUG }}
          JD_USER_AGENT: ${{ secrets.JD_USER_AGENT }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}